import{a as f,S as y,i as c}from"./assets/vendor-RTzsIgW4.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const p=f.create({baseURL:"https://pixabay.com/api/"}),g=s=>p.get("",{params:{key:"55362008-0a0d101fe7347dac3fa7e75ec",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:"9"}}),l=document.querySelector(".gallery"),u=document.querySelector(".loader"),i={gallery:new y(".gallery a"),createGallery(s){const a=s.map(r=>`<li class="galleryItem">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" />
          <ul class="informationList">
            <li class="informationItem">Likes <span class="infoAmount">${r.likes}</span></li>
            <li class="informationItem">Views <span class="infoAmount">${r.views}</span></li>
            <li class="informationItem">Comments <span class="infoAmount">${r.comments}</span></li>
            <li class="informationItem">Downloads <span class="infoAmount">${r.downloads}</span></li>
          </ul>
        </a>
      </li>`).join("");return l.innerHTML=a,this.gallery.refresh(),l},waitForImages(s){const r=[...s.querySelectorAll("img")].map(o=>new Promise(e=>{o.complete?e():o.addEventListener("load",e)}));return Promise.all(r)},clearGallery(){l.innerHTML=""},showGallery(){l.classList.add("isActiveGallery")},hideGallery(){l.classList.remove("isActiveGallery")},showLoader(){u.classList.add("isActive")},hideLoader(){u.classList.remove("isActive")}},d=document.querySelector(".form"),m={maxWidth:"550px",position:"topRight"},h=s=>{s.preventDefault();const a=s.target.elements["search-text"].value.trim();if(a===""){c.error({title:"Error",message:"Search query is empty",...m});return}i.showLoader(),i.clearGallery(),i.hideGallery(),g(a).then(r=>{if(r.data.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");const o=i.createGallery(r.data.hits);return i.waitForImages(o).then(()=>i.showGallery()).catch(e=>c.error({title:"Error",message:e.message,...m}))}).catch(r=>c.error({title:"Error",message:r.message,...m})).finally(()=>{i.hideLoader(),d.reset()})};d.addEventListener("submit",h);
//# sourceMappingURL=index.js.map
