import{a as f,S as y,i as c}from"./assets/vendor-RTzsIgW4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const p=f.create({baseURL:"https://pixabay.com/api/"}),g=a=>new Promise(t=>{p.get("",{params:{key:"55362008-0a0d101fe7347dac3fa7e75ec",q:a,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:"9"}}).then(s=>t(s.data))}),n=document.querySelector(".gallery"),u=document.querySelector(".loader"),h=a=>{const t=a.map(r=>`<li class="galleryItem">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" />
          <ul class="informationList">
            <li class="informationItem">Likes <span class="infoAmount">${r.likes}</span></li>
            <li class="informationItem">Views <span class="infoAmount">${r.views}</span></li>
            <li class="informationItem">Comments <span class="infoAmount">${r.comments}</span></li>
            <li class="informationItem">Downloads <span class="infoAmount">${r.downloads}</span></li>
          </ul>
        </a>
      </li>`).join("");return n.innerHTML=t,new y(".gallery a").refresh(),n},L=a=>{const s=[...a.querySelectorAll("img")].map(r=>new Promise(e=>{r.complete?e():r.addEventListener("load",e)}));return Promise.all(s)},w=()=>{n.innerHTML=""},v=()=>{n.classList.add("isActiveGallery")},S=()=>{n.classList.remove("isActiveGallery")},A=()=>{u.classList.add("isActive")},G=()=>{u.classList.remove("isActive")},i={createGallery:h,clearGallery:w,showGallery:v,hideGallery:S,showLoader:A,hideLoader:G,waitForImages:L},d=document.querySelector(".form"),m={maxWidth:"550px",position:"topRight"},I=a=>{a.preventDefault();const t=a.target.elements["search-text"].value.trim();if(t===""){c.error({title:"Error",message:"Search query is empty",...m});return}i.showLoader(),i.clearGallery(),i.hideGallery(),g(t).then(s=>{if(s.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");const r=i.createGallery(s.hits);return i.waitForImages(r).then(()=>i.showGallery()).catch(e=>c.error({title:"Error",message:e.message,...m}))}).catch(s=>c.error({title:"Error",message:s.message,...m})).finally(()=>{i.hideLoader(),d.reset()})};d.addEventListener("submit",I);
//# sourceMappingURL=index.js.map
