import{a as d,S as f,i as l}from"./assets/vendor-RTzsIgW4.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const p=d.create({baseURL:"https://pixabay.com/api/"}),g=o=>p.get("",{params:{key:"55362008-0a0d101fe7347dac3fa7e75ec",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:"9"}}).then(r=>r.data),i=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=new f(".gallery a"),h=o=>{const r=o.map(t=>`<li class="galleryItem">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" />
          <ul class="informationList">
            <li class="informationItem">Likes <span class="infoAmount">${t.likes}</span></li>
            <li class="informationItem">Views <span class="infoAmount">${t.views}</span></li>
            <li class="informationItem">Comments <span class="infoAmount">${t.comments}</span></li>
            <li class="informationItem">Downloads <span class="infoAmount">${t.downloads}</span></li>
          </ul>
        </a>
      </li>`).join("");return i.innerHTML=r,y.refresh(),i},L=o=>{const t=[...o.querySelectorAll("img")].map(a=>new Promise(e=>{a.complete?e():a.addEventListener("load",e)}));return Promise.all(t)},w=()=>{i.innerHTML=""},v=()=>{i.classList.add("isActiveGallery")},A=()=>{i.classList.remove("isActiveGallery")},S=()=>{m.classList.add("isActive")},b=()=>{m.classList.remove("isActive")},u=document.querySelector(".form"),c={maxWidth:"550px",position:"topRight"},q=o=>{o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(r===""){l.error({title:"Error",message:"Search query is empty",...c});return}S(),A(),w(),g(r).then(t=>{if(t.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");const a=h(t.hits);return L(a).then(()=>v()).catch(e=>l.error({title:"Error",message:e.message,...c}))}).catch(t=>l.error({title:"Error",message:t.message,...c})).finally(()=>{b(),u.reset()})};u.addEventListener("submit",q);
//# sourceMappingURL=index.js.map
